"""asdfawesg migration

Revision ID: d29cb4208fda
Revises: 79de1040f0d3
Create Date: 2017-10-31 21:44:11.963611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29cb4208fda'
down_revision = '79de1040f0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('pitches_user_fkey', 'pitches', type_='foreignkey')
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'])
    op.drop_column('pitches', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.create_foreign_key('pitches_user_fkey', 'pitches', 'users', ['user'], ['id'])
    op.drop_column('pitches', 'user_id')
    # ### end Alembic commands ###
